#!/bin/bash

GROUP_ADDRESS='ff15::33'
INTERFACE='eth0'
PORT='5001'
HOPS=15
DELAY=1
MESSAGE='AllOfYourBasesAreBelongToUs'

./difusor $MESSAGE $GROUP_ADDRESS $INTERFACE $PORT $DELAY $HOPS &

./suscriptor $GROUP_ADDRESS $INTERFACE $PORT &
./suscriptor $GROUP_ADDRESS $INTERFACE $PORT &
./suscriptor $GROUP_ADDRESS $INTERFACE $PORT &

exit 0
